version: "3.6"

services:
    db:
        image: postgres:latest
        environment:
            POSTGRES_DB: your_database_name
            POSTGRES_USER: your_username
            POSTGRES_PASSWORD: your_password
            POSTGRES_HOST_AUTH_METHOD: trust
        ports:
            - "5434:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U your_username -d your_database_name"]
            interval: 5s
            timeout: 5s
            retries: 10

    flights:
        container_name: flights
        build:
            context: ./flights
        ports:
            - "8000:8000"
        environment:
            DATABASE_URL: postgresql+psycopg2://your_username:your_password@db:5432/your_database_name
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
            interval: 30s
            timeout: 10s
            retries: 3
        depends_on:
            db:
                condition: service_healthy

    tickets:
        container_name: tickets
        build:
            context: ./tickets
        ports:
            - "8001:8000"
        environment:
            DATABASE_URL: postgresql+psycopg2://your_username:your_password@db:5432/your_database_name
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:8001/health" ]
            interval: 30s
            timeout: 10s
            retries: 3
        depends_on:
            db:
                condition: service_healthy
